from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path
from typing import List, Optional

import numpy as np
import pandas as pd
from shapely.geometry import Point, Polygon


FILE_NAME_PATTERN = re.compile(
    r"^(?P<subject_id>[^_]+)_(?P<task>[^_]+)_(?P<step_id>-?\d+)_(?P<event>grasp|release)_(?P<block_id>-?\d+)_(?P<label>[01])$"
)

INPUT_FEATURE_COLUMNS = [
    "timestamp",
    "event",
    "gaze_x_table_affine_cm",
    "gaze_y_table_affine_cm",
    "screen_confidence_right",
    "screen_confidence_left",
    "screen_diameter_right",
    "screen_diameter_left",
    "table_confidence_right",
    "table_confidence_left",
    "table_diameter_right",
    "table_diameter_left",
    "target_x_table_srt_cm0",
    "target_y_table_srt_cm0",
    "target_x_table_srt_cm1",
    "target_y_table_srt_cm1",
    "target_x_table_srt_cm2",
    "target_y_table_srt_cm2",
    "target_x_table_srt_cm3",
    "target_y_table_srt_cm3",
    "target_x_table_dst_cm0",
    "target_y_table_dst_cm0",
    "target_x_table_dst_cm1",
    "target_y_table_dst_cm1",
    "target_x_table_dst_cm2",
    "target_y_table_dst_cm2",
    "target_x_table_dst_cm3",
    "target_y_table_dst_cm3",
]

OUTPUT_COLUMNS = [
    "timestamp",
    "event",
    "screen_confidence_right",
    "screen_confidence_left",
    "screen_diameter_right",
    "screen_diameter_left",
    "table_confidence_right",
    "table_confidence_left",
    "table_diameter_right",
    "table_diameter_left",
    "gaze_x_table_affine_cm",
    "gaze_y_table_affine_cm",
    "deviation_srt_cm",
    "deviation_dst_cm",
    "deviation_cm",
    "target_x_table_srt_cm0",
    "target_y_table_srt_cm0",
    "target_x_table_srt_cm1",
    "target_y_table_srt_cm1",
    "target_x_table_srt_cm2",
    "target_y_table_srt_cm2",
    "target_x_table_srt_cm3",
    "target_y_table_srt_cm3",
    "target_x_table_dst_cm0",
    "target_y_table_dst_cm0",
    "target_x_table_dst_cm1",
    "target_y_table_dst_cm1",
    "target_x_table_dst_cm2",
    "target_y_table_dst_cm2",
    "target_x_table_dst_cm3",
    "target_y_table_dst_cm3",
]

JSONL_SCALAR_COLUMNS = [
    "timestamp",
    "event",
    "deviation_srt_cm",
    "deviation_dst_cm",
    "deviation_cm",
]

MERGED_GAZE_COLUMN = "gaze_x_y_table_affine_cm"
MERGED_SCREEN_CONFIDENCE_COLUMN = "screen_confidence_left_right"
MERGED_SCREEN_DIAMETER_COLUMN = "screen_diameter_left_right"
MERGED_TABLE_CONFIDENCE_COLUMN = "table_confidence_left_right"
MERGED_TABLE_DIAMETER_COLUMN = "table_diameter_left_right"
MERGED_SOURCE_TARGET_COLUMN = "target_x_y_table_srt_cm"
MERGED_DESTINATION_TARGET_COLUMN = "target_x_y_table_dst_cm"

SOURCE_TARGET_COLUMNS = [
    ("target_x_table_srt_cm0", "target_y_table_srt_cm0"),
    ("target_x_table_srt_cm1", "target_y_table_srt_cm1"),
    ("target_x_table_srt_cm2", "target_y_table_srt_cm2"),
    ("target_x_table_srt_cm3", "target_y_table_srt_cm3"),
]

DESTINATION_TARGET_COLUMNS = [
    ("target_x_table_dst_cm0", "target_y_table_dst_cm0"),
    ("target_x_table_dst_cm1", "target_y_table_dst_cm1"),
    ("target_x_table_dst_cm2", "target_y_table_dst_cm2"),
    ("target_x_table_dst_cm3", "target_y_table_dst_cm3"),
]


def find_slice_files(input_dir: Path) -> List[Path]:
    """Find all slice CSV files generated by the second preprocessing step."""

    return sorted(path for path in input_dir.rglob("*.csv") if path.is_file())


def parse_slice_metadata(file_path: Path) -> Optional[dict[str, str]]:
    """Parse metadata encoded in the slice file name."""

    match = FILE_NAME_PATTERN.match(file_path.stem)
    if match is None:
        return None
    return match.groupdict()


def build_polygon_from_row(row: pd.Series, point_columns: List[tuple[str, str]]) -> Polygon:
    """Build a target polygon from one row of corner coordinates."""

    points = [
        (float(row[x_column]), float(row[y_column]))
        for x_column, y_column in point_columns
    ]
    polygon = Polygon(points)
    if polygon.is_empty or not polygon.is_valid:
        polygon = polygon.buffer(0)
    return polygon


def compute_point_polygon_distance(x: float, y: float, polygon: Polygon) -> float:
    """Compute the shortest physical distance from a point to a polygon."""

    if pd.isna(x) or pd.isna(y):
        return float("nan")
    point = Point(float(x), float(y))
    return float(point.distance(polygon))


def json_safe_value(value: object) -> object:
    """Convert pandas/numpy values into JSON-safe Python objects."""

    if isinstance(value, np.ndarray):
        return [json_safe_value(item) for item in value.tolist()]
    if isinstance(value, (list, tuple)):
        return [json_safe_value(item) for item in value]
    if isinstance(value, np.generic):
        value = value.item()
    if pd.isna(value):
        return None
    return value


def compute_deviation_sequence(df: pd.DataFrame) -> pd.DataFrame:
    """Compute deviation sequences for source and destination polygons."""

    if df.empty:
        return pd.DataFrame(columns=OUTPUT_COLUMNS)

    valid_mask = df["gaze_x_table_affine_cm"].notna() & df["gaze_y_table_affine_cm"].notna()
    valid_df = df.loc[valid_mask].copy()
    if valid_df.empty:
        return pd.DataFrame(columns=OUTPUT_COLUMNS)

    first_row = valid_df.iloc[0]
    source_polygon = build_polygon_from_row(first_row, SOURCE_TARGET_COLUMNS)
    destination_polygon = build_polygon_from_row(first_row, DESTINATION_TARGET_COLUMNS)

    valid_df["deviation_srt_cm"] = [
        compute_point_polygon_distance(x, y, source_polygon)
        for x, y in zip(valid_df["gaze_x_table_affine_cm"], valid_df["gaze_y_table_affine_cm"])
    ]
    valid_df["deviation_dst_cm"] = [
        compute_point_polygon_distance(x, y, destination_polygon)
        for x, y in zip(valid_df["gaze_x_table_affine_cm"], valid_df["gaze_y_table_affine_cm"])
    ]

    event_series = valid_df["event"].fillna("").astype(str).str.strip().str.lower()
    active_deviation = pd.Series(np.nan, index=valid_df.index, dtype="float64")
    active_deviation.loc[event_series.eq("grasp")] = valid_df.loc[event_series.eq("grasp"), "deviation_srt_cm"]
    active_deviation.loc[event_series.eq("release")] = valid_df.loc[event_series.eq("release"), "deviation_dst_cm"]
    valid_df["deviation_cm"] = active_deviation

    return valid_df.reindex(columns=OUTPUT_COLUMNS)


def build_jsonl_record(row: pd.Series) -> dict[str, object]:
    """Build one JSON-serializable record from a flat output row."""

    record = {column: json_safe_value(row[column]) for column in JSONL_SCALAR_COLUMNS}
    record[MERGED_SCREEN_CONFIDENCE_COLUMN] = [
        json_safe_value(row["screen_confidence_left"]),
        json_safe_value(row["screen_confidence_right"]),
    ]
    record[MERGED_SCREEN_DIAMETER_COLUMN] = [
        json_safe_value(row["screen_diameter_left"]),
        json_safe_value(row["screen_diameter_right"]),
    ]
    record[MERGED_TABLE_CONFIDENCE_COLUMN] = [
        json_safe_value(row["table_confidence_left"]),
        json_safe_value(row["table_confidence_right"]),
    ]
    record[MERGED_TABLE_DIAMETER_COLUMN] = [
        json_safe_value(row["table_diameter_left"]),
        json_safe_value(row["table_diameter_right"]),
    ]
    record[MERGED_GAZE_COLUMN] = [
        json_safe_value(row["gaze_x_table_affine_cm"]),
        json_safe_value(row["gaze_y_table_affine_cm"]),
    ]
    record[MERGED_SOURCE_TARGET_COLUMN] = [
        [json_safe_value(row[x_column]), json_safe_value(row[y_column])]
        for x_column, y_column in SOURCE_TARGET_COLUMNS
    ]
    record[MERGED_DESTINATION_TARGET_COLUMN] = [
        [json_safe_value(row[x_column]), json_safe_value(row[y_column])]
        for x_column, y_column in DESTINATION_TARGET_COLUMNS
    ]
    return record


def write_jsonl_file(df: pd.DataFrame, output_path: Path) -> None:
    """Write one JSON object per line."""

    with output_path.open("w", encoding="utf-8") as handle:
        for row in df.itertuples(index=False):
            record = build_jsonl_record(pd.Series(row._asdict()))
            handle.write(json.dumps(record, ensure_ascii=False))
            handle.write("\n")


def load_slice_dataframe(file_path: Path) -> pd.DataFrame:
    """Load one slice file."""

    return pd.read_csv(file_path)


def process_slice_file(
    file_path: Path,
    output_root: Path,
    include_failures: bool,
    min_output_length: int,
) -> int:
    """Process one slice file and write its deviation sequence if eligible."""

    metadata = parse_slice_metadata(file_path)
    if metadata is None:
        logging.info("Skip file with unexpected name: %s", file_path.name)
        return 0

    if not include_failures and metadata["label"] != "1":
        return 0

    df = load_slice_dataframe(file_path)
    if df.empty:
        logging.info("Skip empty slice file: %s", file_path)
        return 0

    missing_columns = [column for column in INPUT_FEATURE_COLUMNS if column not in df.columns]
    if missing_columns:
        logging.warning("Skip %s because columns are missing: %s", file_path, ", ".join(missing_columns))
        return 0

    output_df = compute_deviation_sequence(df)
    if output_df.empty:
        logging.info("No valid affine gaze rows in %s", file_path)
        return 0

    if len(output_df) < min_output_length:
        logging.info(
            "Skip %s because computed output length %d is below threshold %d",
            file_path,
            len(output_df),
            min_output_length,
        )
        return 0

    output_root.mkdir(parents=True, exist_ok=True)
    jsonl_output_path = output_root / f"{file_path.stem}.jsonl"
    write_jsonl_file(output_df, jsonl_output_path)
    return 1


def build_argument_parser() -> argparse.ArgumentParser:
    """Build command line arguments."""

    parser = argparse.ArgumentParser(
        description="Compute gaze-to-block deviation sequences from GAIPAT slice CSV files and export JSONL outputs."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root directory.",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=None,
        help="Directory containing slice CSV files. Defaults to <repo-root>/slice_dataframes.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory where deviation outputs will be written. Defaults to <repo-root>/block_deviation_sequences.",
    )
    parser.add_argument(
        "--include-failures",
        action="store_true",
        help="Also process files whose name label is 0. By default only successful slices are exported.",
    )
    parser.add_argument(
        "--min-output-length",
        type=int,
        default=5,
        help="Minimum number of rows required after deviation computation. Shorter results are discarded.",
    )
    return parser


def main() -> None:
    """Entry point."""

    args = build_argument_parser().parse_args()
    repo_root = args.repo_root
    input_dir = args.input_dir or (repo_root / "slice_dataframes")
    output_dir = args.output_dir or (repo_root / "block_deviation_sequences")
    output_dir.mkdir(parents=True, exist_ok=True)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[
            logging.FileHandler(output_dir / "deviation_sequences.log"),
            logging.StreamHandler(),
        ],
    )

    slice_files = find_slice_files(input_dir)
    if not slice_files:
        logging.warning("No slice CSV files found under %s", input_dir)
        return

    exported_count = 0
    for file_path in slice_files:
        exported_count += process_slice_file(
            file_path,
            output_dir,
            args.include_failures,
            args.min_output_length,
        )

    logging.info("Done. Exported %d deviation sequences.", exported_count)


if __name__ == "__main__":
    main()
