from __future__ import annotations

import argparse
import json
import logging
import math
import pickle
import re
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd


FILE_NAME_PATTERN = re.compile(
    r"^(?P<subject_id>[^_]+)_(?P<task>[^_]+)_(?P<step_id>-?\d+)_(?P<event>grasp|release)_(?P<block_id>-?\d+)_(?P<label>[01])$"
)

FEATURE_COLUMNS = [
    "distance_median",
    "distance_q10",
    "distance_q90",
    "distance_std",
    "distance_slope",
    "diff_abs_mean",
    "distance_lag1_autocorr",
    "near_ratio_tau",
    "longest_near_run_ratio",
    "time_to_first_near_ratio",
]

DEFAULT_CLUSTER_NAMES = {
    "focused": "Focused",
    "searching": "Searching",
    "wandering": "Wandering",
    "noise": "Noise",
    "distracted": "Distracted",
}


def find_jsonl_files(input_dir: Path) -> list[Path]:
    """Find deviation sequence JSONL files generated by step 03."""

    return sorted(path for path in input_dir.rglob("*.jsonl") if path.is_file())


def parse_sequence_metadata(file_path: Path) -> dict[str, object] | None:
    """Parse slice metadata encoded in the JSONL file name."""

    match = FILE_NAME_PATTERN.match(file_path.stem)
    if match is None:
        return None

    metadata: dict[str, object] = match.groupdict()
    metadata["step_id"] = int(metadata["step_id"])
    metadata["block_id"] = int(metadata["block_id"])
    metadata["label"] = int(metadata["label"])
    return metadata


def to_finite_float(value: object) -> float:
    """Convert one JSON scalar to a finite float, or NaN when unavailable."""

    if value is None:
        return float("nan")
    try:
        result = float(value)
    except (TypeError, ValueError):
        return float("nan")
    if not math.isfinite(result):
        return float("nan")
    return result


def read_jsonl_records(file_path: Path) -> list[dict[str, object]]:
    """Read all JSON records from one sequence file."""

    records: list[dict[str, object]] = []
    with file_path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{file_path}:{line_number} contains invalid JSON: {exc}") from exc
            if not isinstance(record, dict):
                raise ValueError(f"{file_path}:{line_number} is not a JSON object")
            records.append(record)
    return records


def extract_deviation_sequence(records: Sequence[dict[str, object]]) -> tuple[np.ndarray, np.ndarray]:
    """Extract finite deviation values and their matching timestamps."""

    deviations: list[float] = []
    timestamps: list[float] = []

    for record in records:
        deviation = to_finite_float(record.get("deviation_cm"))
        if math.isnan(deviation):
            continue
        deviations.append(deviation)
        timestamps.append(to_finite_float(record.get("timestamp")))

    return np.asarray(deviations, dtype="float64"), np.asarray(timestamps, dtype="float64")


def normalize_time_axis(timestamps: np.ndarray, sequence_length: int) -> np.ndarray:
    """Build a stable 0..1 time axis from timestamps, falling back to row index."""

    if sequence_length <= 1:
        return np.zeros(sequence_length, dtype="float64")

    finite_mask = np.isfinite(timestamps)
    if finite_mask.sum() == sequence_length:
        min_timestamp = float(np.min(timestamps))
        max_timestamp = float(np.max(timestamps))
        if max_timestamp > min_timestamp:
            return (timestamps - min_timestamp) / (max_timestamp - min_timestamp)

    return np.linspace(0.0, 1.0, sequence_length, dtype="float64")


def longest_true_run(mask: np.ndarray) -> int:
    """Return the longest contiguous run of True values."""

    longest = 0
    current = 0
    for value in mask:
        if bool(value):
            current += 1
            longest = max(longest, current)
        else:
            current = 0
    return longest


def lag1_autocorrelation(values: np.ndarray) -> float:
    """Compute lag-1 autocorrelation with safe handling for short/flat data."""

    if len(values) < 2:
        return 0.0

    previous_values = values[:-1]
    next_values = values[1:]
    previous_std = float(np.std(previous_values))
    next_std = float(np.std(next_values))
    if previous_std == 0.0 or next_std == 0.0:
        return 0.0

    corr = float(np.corrcoef(previous_values, next_values)[0, 1])
    if not math.isfinite(corr):
        return 0.0
    return corr


def linear_slope(values: np.ndarray, timestamps: np.ndarray) -> float:
    """Fit distance slope against a normalized time axis."""

    if len(values) < 2:
        return 0.0

    x_axis = normalize_time_axis(timestamps, len(values))
    if float(np.max(x_axis)) == float(np.min(x_axis)):
        return 0.0

    slope = float(np.polyfit(x_axis, values, deg=1)[0])
    if not math.isfinite(slope):
        return 0.0
    return slope


def extract_sequence_features(
    deviations: np.ndarray,
    timestamps: np.ndarray | None = None,
    near_threshold_cm: float = 2.0,
) -> dict[str, float]:
    """Compute the fixed-length feature vector described in cluster.md."""

    if timestamps is None:
        timestamps = np.asarray([], dtype="float64")
    if len(timestamps) != len(deviations):
        timestamps = np.full(len(deviations), np.nan, dtype="float64")

    if len(deviations) == 0:
        raise ValueError("Cannot extract features from an empty deviation sequence")

    near_mask = deviations < near_threshold_cm
    near_indices = np.flatnonzero(near_mask)
    if len(near_indices):
        time_to_first_near_ratio = float(near_indices[0] / max(len(deviations) - 1, 1))
    else:
        time_to_first_near_ratio = 1.0

    differences = np.diff(deviations)

    return {
        "distance_median": float(np.median(deviations)),
        "distance_q10": float(np.quantile(deviations, 0.10)),
        "distance_q90": float(np.quantile(deviations, 0.90)),
        "distance_std": float(np.std(deviations, ddof=0)),
        "distance_slope": linear_slope(deviations, timestamps),
        "diff_abs_mean": float(np.mean(np.abs(differences))) if len(differences) else 0.0,
        "distance_lag1_autocorr": lag1_autocorrelation(deviations),
        "near_ratio_tau": float(np.mean(near_mask)),
        "longest_near_run_ratio": float(longest_true_run(near_mask) / len(deviations)),
        "time_to_first_near_ratio": time_to_first_near_ratio,
    }


def load_sequence_as_feature_row(file_path: Path, near_threshold_cm: float) -> dict[str, object] | None:
    """Load one JSONL file and convert it to one clustering sample row."""

    metadata = parse_sequence_metadata(file_path)
    if metadata is None:
        logging.info("Skip file with unexpected name: %s", file_path.name)
        return None

    records = read_jsonl_records(file_path)
    deviations, timestamps = extract_deviation_sequence(records)
    if len(deviations) == 0:
        logging.info("Skip %s because it has no finite deviation_cm values", file_path)
        return None

    feature_row: dict[str, object] = {
        "sequence_id": file_path.stem,
        "source_file": str(file_path),
        "n_points": int(len(deviations)),
        **metadata,
    }
    feature_row.update(extract_sequence_features(deviations, timestamps, near_threshold_cm))
    return feature_row


def build_raw_feature_table(input_dir: Path, near_threshold_cm: float) -> pd.DataFrame:
    """Build the raw, unscaled slice-level feature table."""

    rows: list[dict[str, object]] = []
    for file_path in find_jsonl_files(input_dir):
        row = load_sequence_as_feature_row(file_path, near_threshold_cm)
        if row is not None:
            rows.append(row)

    columns = [
        "sequence_id",
        "source_file",
        "subject_id",
        "task",
        "step_id",
        "event",
        "block_id",
        "label",
        "n_points",
        *FEATURE_COLUMNS,
    ]
    return pd.DataFrame(rows, columns=columns)


def choose_component_count(sample_count: int, requested_components: int) -> int:
    """Keep GMM component count valid for the available event-specific samples."""

    if sample_count < 1:
        return 0
    return max(1, min(int(requested_components), sample_count))


def count_unique_rows(matrix: np.ndarray) -> int:
    """Count unique rows after rounding tiny floating-point noise."""

    if len(matrix) == 0:
        return 0
    rounded = np.round(matrix.astype("float64"), decimals=10)
    return int(np.unique(rounded, axis=0).shape[0])


def import_sklearn_cluster_dependencies():
    """Import sklearn only when clustering is executed."""

    try:
        from sklearn.mixture import GaussianMixture
        from sklearn.preprocessing import PowerTransformer
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "scikit-learn is required for clustering. Install it on the server with: "
            "pip install scikit-learn"
        ) from exc
    return GaussianMixture, PowerTransformer


def fit_event_cluster_model(
    event_features: pd.DataFrame,
    n_components: int,
    random_state: int,
    covariance_type: str,
    max_iter: int,
):
    """Fit Yeo-Johnson transformer and GMM for one event type."""

    GaussianMixture, PowerTransformer = import_sklearn_cluster_dependencies()
    component_count = choose_component_count(len(event_features), n_components)
    if component_count == 0:
        raise ValueError("Cannot fit a cluster model with zero samples")

    feature_matrix = event_features[FEATURE_COLUMNS].to_numpy(dtype="float64")
    transformed_matrix = np.zeros_like(feature_matrix, dtype="float64")
    variable_mask = np.std(feature_matrix, axis=0) > 1e-12
    transformer = None

    # PowerTransformer is undefined for fully constant or one-row subsets.
    # Keep those columns as zeros after standardization, which is equivalent
    # to removing non-informative variance from the GMM feature space.
    if len(event_features) >= 2 and bool(variable_mask.any()):
        transformer = PowerTransformer(method="yeo-johnson", standardize=True)
        transformed_matrix[:, variable_mask] = transformer.fit_transform(feature_matrix[:, variable_mask])

    unique_rows = count_unique_rows(transformed_matrix)
    component_count = max(1, min(component_count, unique_rows))

    model = GaussianMixture(
        n_components=component_count,
        covariance_type=covariance_type,
        random_state=random_state,
        max_iter=max_iter,
        n_init=10,
        reg_covar=1e-6,
    )
    clusters = model.fit_predict(transformed_matrix)
    probabilities = model.predict_proba(transformed_matrix)
    max_probabilities = probabilities.max(axis=1)

    return transformer, model, variable_mask, transformed_matrix, clusters, probabilities, max_probabilities


def summarize_cluster_semantics(success_rows: pd.DataFrame) -> dict[int, str]:
    """Assign human-readable cluster names from raw feature profiles."""

    if success_rows.empty:
        return {}

    cluster_summary = success_rows.groupby("cluster_id")[FEATURE_COLUMNS].mean()
    if cluster_summary.empty:
        return {}

    score_table = pd.DataFrame(index=cluster_summary.index)
    score_table["focused"] = (
        cluster_summary["near_ratio_tau"].rank(ascending=False)
        + cluster_summary["distance_median"].rank(ascending=True)
        + cluster_summary["distance_std"].rank(ascending=True)
    )
    score_table["searching"] = (
        cluster_summary["distance_slope"].rank(ascending=True)
        + cluster_summary["time_to_first_near_ratio"].rank(ascending=False)
    )
    score_table["wandering"] = (
        cluster_summary["distance_std"].rank(ascending=False)
        + cluster_summary["longest_near_run_ratio"].rank(ascending=True)
    )
    score_table["noise"] = (
        cluster_summary["diff_abs_mean"].rank(ascending=False)
        + cluster_summary["distance_lag1_autocorr"].rank(ascending=True)
    )

    available_clusters = set(int(cluster_id) for cluster_id in cluster_summary.index)
    assignments: dict[int, str] = {}
    for semantic_key in ["focused", "searching", "wandering", "noise"]:
        if not available_clusters:
            break
        best_cluster = min(
            available_clusters,
            key=lambda cluster_id: float(score_table.loc[cluster_id, semantic_key]),
        )
        assignments[best_cluster] = DEFAULT_CLUSTER_NAMES[semantic_key]
        available_clusters.remove(best_cluster)

    for cluster_id in available_clusters:
        assignments[cluster_id] = f"Cluster_{cluster_id}"
    return assignments


def build_event_assignments(
    event_features: pd.DataFrame,
    clusters: np.ndarray,
    max_probabilities: np.ndarray,
) -> pd.DataFrame:
    """Build sample-level assignments, applying the mandatory failure override."""

    assignments = event_features.copy()
    assignments["cluster_id"] = clusters.astype(int)
    assignments["cluster_probability"] = max_probabilities.astype(float)

    success_mask = assignments["label"].astype(int).eq(1)
    semantic_names = summarize_cluster_semantics(assignments.loc[success_mask])
    assignments["cluster_name"] = assignments["cluster_id"].map(semantic_names).fillna(
        assignments["cluster_id"].map(lambda value: f"Cluster_{value}")
    )
    assignments.loc[~success_mask, "cluster_name"] = DEFAULT_CLUSTER_NAMES["distracted"]
    assignments.loc[~success_mask, "cluster_id"] = -1
    return assignments


def write_pickle(path: Path, payload: object) -> None:
    """Persist fitted model artifacts."""

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as handle:
        pickle.dump(payload, handle)


def write_event_probability_table(
    output_path: Path,
    event_features: pd.DataFrame,
    probabilities: np.ndarray,
) -> None:
    """Write soft cluster probabilities for one event model."""

    probability_columns = [f"gmm_probability_cluster_{index}" for index in range(probabilities.shape[1])]
    probability_df = pd.DataFrame(probabilities, columns=probability_columns)
    id_columns = ["sequence_id", "event", "label"]
    output_df = pd.concat([event_features[id_columns].reset_index(drop=True), probability_df], axis=1)
    output_df.to_csv(output_path, index=False)


def build_cluster_summary(assignments: pd.DataFrame) -> pd.DataFrame:
    """Summarize assignments by event and final cluster name."""

    if assignments.empty:
        return pd.DataFrame()

    grouped = assignments.groupby(["event", "cluster_id", "cluster_name"], dropna=False)
    summary = grouped.agg(
        sample_count=("sequence_id", "count"),
        success_count=("label", lambda values: int(np.sum(np.asarray(values, dtype=int) == 1))),
        failure_count=("label", lambda values: int(np.sum(np.asarray(values, dtype=int) == 0))),
        distance_median_mean=("distance_median", "mean"),
        distance_q10_mean=("distance_q10", "mean"),
        distance_q90_mean=("distance_q90", "mean"),
        distance_std_mean=("distance_std", "mean"),
        distance_slope_mean=("distance_slope", "mean"),
        diff_abs_mean_mean=("diff_abs_mean", "mean"),
        near_ratio_tau_mean=("near_ratio_tau", "mean"),
        longest_near_run_ratio_mean=("longest_near_run_ratio", "mean"),
        time_to_first_near_ratio_mean=("time_to_first_near_ratio", "mean"),
    )
    return summary.reset_index().sort_values(["event", "cluster_id"]).reset_index(drop=True)


def resample_sequence(values: np.ndarray, target_length: int) -> np.ndarray:
    """Resample one variable-length sequence onto a fixed 0..1 grid."""

    if len(values) == 0:
        return np.full(target_length, np.nan, dtype="float64")
    if len(values) == 1:
        return np.full(target_length, float(values[0]), dtype="float64")

    old_axis = np.linspace(0.0, 1.0, len(values), dtype="float64")
    new_axis = np.linspace(0.0, 1.0, target_length, dtype="float64")
    return np.interp(new_axis, old_axis, values)


def iter_assignment_sequences(assignments: pd.DataFrame) -> Iterable[tuple[pd.Series, np.ndarray]]:
    """Yield assignment rows with their source deviation sequences."""

    for _, row in assignments.iterrows():
        records = read_jsonl_records(Path(str(row["source_file"])))
        deviations, _ = extract_deviation_sequence(records)
        if len(deviations):
            yield row, deviations


def write_mean_curve_tables(
    assignments: pd.DataFrame,
    output_dir: Path,
    resample_points: int,
) -> pd.DataFrame:
    """Write average deviation curves per event/cluster to CSV."""

    if assignments.empty:
        return pd.DataFrame()

    curve_rows: list[dict[str, object]] = []
    bucket: dict[tuple[str, int, str], list[np.ndarray]] = {}
    for row, deviations in iter_assignment_sequences(assignments):
        key = (str(row["event"]), int(row["cluster_id"]), str(row["cluster_name"]))
        bucket.setdefault(key, []).append(resample_sequence(deviations, resample_points))

    for (event, cluster_id, cluster_name), curves in sorted(bucket.items()):
        matrix = np.vstack(curves)
        mean_curve = np.nanmean(matrix, axis=0)
        for point_index, value in enumerate(mean_curve):
            curve_rows.append(
                {
                    "event": event,
                    "cluster_id": cluster_id,
                    "cluster_name": cluster_name,
                    "normalized_time": point_index / max(resample_points - 1, 1),
                    "mean_deviation_cm": float(value),
                    "sample_count": len(curves),
                }
            )

    curve_df = pd.DataFrame(curve_rows)
    curve_df.to_csv(output_dir / "cluster_mean_curves.csv", index=False)
    return curve_df


def maybe_write_mean_curve_plots(curve_df: pd.DataFrame, output_dir: Path) -> None:
    """Write one average-curve PNG per event when matplotlib is available."""

    if curve_df.empty:
        return

    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError:
        logging.warning("matplotlib is not installed; skip mean curve PNG plots")
        return

    for event, event_curves in curve_df.groupby("event"):
        fig, ax = plt.subplots(figsize=(9, 5))
        for (_, cluster_name), cluster_curve in event_curves.groupby(["cluster_id", "cluster_name"]):
            ax.plot(
                cluster_curve["normalized_time"],
                cluster_curve["mean_deviation_cm"],
                label=f"{cluster_name} (n={int(cluster_curve['sample_count'].iloc[0])})",
            )
        ax.set_title(f"{event} mean deviation curves")
        ax.set_xlabel("Normalized slice time")
        ax.set_ylabel("Mean deviation (cm)")
        ax.grid(True, alpha=0.3)
        ax.legend()
        fig.tight_layout()
        fig.savefig(output_dir / f"{event}_cluster_mean_curves.png", dpi=160)
        plt.close(fig)


def run_clustering(args: argparse.Namespace) -> None:
    """Execute the complete step-04 clustering pipeline."""

    repo_root = args.repo_root
    input_dir = args.input_dir or (repo_root / "block_deviation_sequences")
    output_dir = args.output_dir or (repo_root / "cluster_results")
    output_dir.mkdir(parents=True, exist_ok=True)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[
            logging.FileHandler(output_dir / "cluster.log"),
            logging.StreamHandler(),
        ],
    )

    raw_features = build_raw_feature_table(input_dir, args.near_threshold_cm)
    if raw_features.empty:
        logging.warning("No valid JSONL deviation sequences found under %s", input_dir)
        return

    raw_features.to_csv(output_dir / "cluster_raw_features.csv", index=False)
    logging.info("Wrote raw feature table with %d samples", len(raw_features))

    if args.features_only:
        logging.info("Features-only mode enabled; skip model fitting")
        return

    all_assignments: list[pd.DataFrame] = []
    for event in ["grasp", "release"]:
        event_features = raw_features.loc[raw_features["event"].eq(event)].reset_index(drop=True)
        if event_features.empty:
            logging.warning("No %s samples available; skip this event model", event)
            continue

        transformer, model, variable_mask, _, clusters, probabilities, max_probabilities = fit_event_cluster_model(
            event_features=event_features,
            n_components=args.n_components,
            random_state=args.random_state,
            covariance_type=args.covariance_type,
            max_iter=args.max_iter,
        )
        write_pickle(
            output_dir / f"{event}_gmm_model.pkl",
            {
                "event": event,
                "feature_columns": FEATURE_COLUMNS,
                "variable_feature_mask": variable_mask,
                "near_threshold_cm": args.near_threshold_cm,
                "transformer": transformer,
                "model": model,
            },
        )
        write_event_probability_table(output_dir / f"{event}_cluster_probabilities.csv", event_features, probabilities)

        assignments = build_event_assignments(event_features, clusters, max_probabilities)
        all_assignments.append(assignments)
        logging.info(
            "Fitted %s GMM with %d samples and %d components",
            event,
            len(event_features),
            model.n_components,
        )

    if not all_assignments:
        logging.warning("No event model was fitted")
        return

    assignments = pd.concat(all_assignments, ignore_index=True)
    assignments.to_csv(output_dir / "cluster_assignments.csv", index=False)

    summary = build_cluster_summary(assignments)
    summary.to_csv(output_dir / "cluster_summary.csv", index=False)

    curve_df = write_mean_curve_tables(assignments, output_dir, args.resample_points)
    if not args.no_plots:
        maybe_write_mean_curve_plots(curve_df, output_dir)

    logging.info("Done. Wrote clustering outputs to %s", output_dir)


def build_argument_parser() -> argparse.ArgumentParser:
    """Build command line arguments."""

    parser = argparse.ArgumentParser(
        description="Cluster GAIPAT step-03 JSONL deviation sequences with Yeo-Johnson + event-specific GMM."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default="/root/autodl-tmp/shenxy/Data/gaipat",
        help="Repository root directory.",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=None,
        help="Directory containing step-03 JSONL files. Defaults to <repo-root>/block_deviation_sequences.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory where clustering outputs will be written. Defaults to <repo-root>/cluster_results.",
    )
    parser.add_argument(
        "--n-components",
        type=int,
        default=3,
        help="Requested GMM component count per event. Automatically reduced when an event has fewer samples.",
    )
    parser.add_argument(
        "--near-threshold-cm",
        type=float,
        default=3.0,
        help="Physical near-target threshold used by near-ratio features.",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed used by GMM.",
    )
    parser.add_argument(
        "--covariance-type",
        choices=["full", "tied", "diag", "spherical"],
        default="full",
        help="GMM covariance type.",
    )
    parser.add_argument(
        "--max-iter",
        type=int,
        default=500,
        help="Maximum GMM EM iterations.",
    )
    parser.add_argument(
        "--resample-points",
        type=int,
        default=100,
        help="Number of normalized points for mean curve exports.",
    )
    parser.add_argument(
        "--features-only",
        action="store_true",
        help="Only write cluster_raw_features.csv. Does not require scikit-learn.",
    )
    parser.add_argument(
        "--no-plots",
        action="store_true",
        help="Skip PNG plot generation and only write CSV outputs.",
    )
    return parser


def main() -> None:
    """Entry point."""

    args = build_argument_parser().parse_args()
    run_clustering(args)


if __name__ == "__main__":
    main()
